### PR TITLE
[OM-88022] Added additional mutex locking to closeAndResetWebSocket method

### PR DESCRIPTION
**Pull request by amd-ibm**
### Intent
 
Prevent a nil race condition when a web socket is reset by the server without sending a close message.

### Fix

Added additional mutex locking to the _closeAndResetWebSocket_ method to avoid a race condition when reestablishing the web socket connection.
Added an additional nil check to _GetConnectionId_ method instead of introducing locking.

### CODE REVIEW

**Comment by ading1977** [comment]
I did a quick search on the usage of `wsTransport.ws`, and feel that it might not have been guarded in all occasions?

image

In general, I think we need to guard all read/write access to it, and make the scope as small as possible. For example:

```
func (wsTransport *ClientWebSocketTransport) closeAndResetWebSocket() {
	if wsTransport.status == Closed {
		return
	}
	wsTransport.status = Closed

	// close WebSocket
	wsTransport.wsMux.Lock()
	defer wsTransport.wsMux.UnLock()
	if wsTransport.ws != nil {
		glog.V(1).Infof("Begin to send websocket Close frame.")
		wsTransport.write(websocket.CloseMessage, []byte{})
		wsTransport.ws.Close()
		wsTransport.ws = nil
	}	
}
```

```
func (wsTransport *ClientWebSocketTransport) GetConnectionId() string {
	if wsTransport.status == Closed {
		return ""
	}
	wsTransport.wsMux.Lock()
	defer wsTransport.wsMux.UnLock()
	if wsTransport.ws == nil {
		return ""
	}
	return wsTransport.ws.RemoteAddr().String() + "::" + wsTransport.ws.LocalAddr().String()
}
```

**Comment by amd-ibm** [comment]
@ading1977 , some of these paths call methods that include locking. For example, the `write` method acquires the locks, so your example above would create a deadlock. That's why I replaced the call to the `write` method in the `closeAndResetWebSocket` with the few non-lock-related commands.

**Comment by ading1977** [comment]
> @ading1977 , some of these paths call methods that include locking. For example, the `write` method acquires the locks, so your example above would create a deadlock. That's why I replaced the call to the `write` method in the `closeAndResetWebSocket` with the few non-lock-related commands.

Yes, I understand that part, which is fine. I was referring to the scope of the mutex to be as small as possible (e.g., do not include the part of `wsTransport.status`) to be absolutely safe. Also, how about the access in the `performWebSocketConnection` where we are writing to the `wsTransport.ws` without a mutex? That might be fine if we are sure there won't be any chance of concurrent access, but I don't know.

**Comment by ading1977** [comment]
> @ading1977 , some of these paths call methods that include locking. For example, the `write` method acquires the locks, so your example above would create a deadlock. That's why I replaced the call to the `write` method in the `closeAndResetWebSocket` with the few non-lock-related commands.

By the way, trying to acquire th lock while already holding the same lock by the same goroutine will not cause a deadlock situation.

**Comment by amd-ibm** [comment]
> 

Are you sure? I'm pretty sure I hit a deadlock on the `write` method, before I hoisted that logic up. I'll try it again.

**Comment by ading1977** [comment]
> > 
> 
> Are you sure? I'm pretty sure I hit a deadlock on the `write` method, before I hoisted that logic up. I'll try it again.

You are right, looks looks go mutex is not reentrant by default.

**Review by ading1977 — APPROVED** [review]

**Review by pankajbatra1 — APPROVED** [review]

**Review by irfanurrehman — APPROVED** [review]

**Pull request merged**
